# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/request/futures/FuturesQueryHistoryEntrustListRequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/request/futures/FuturesQueryHistoryEntrustListRequest.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n:com.huasheng.quant.open.sdk.protobuf.trade.request.futuresB*FuturesQueryHistoryEntrustListRequestProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nAtrade/request/futures/FuturesQueryHistoryEntrustListRequest.proto\"m\n%FuturesQueryHistoryEntrustListRequest\x12\x0e\n\x06pageNo\x18\x01 \x01(\x05\x12\x10\n\x08pageSize\x18\x02 \x01(\x05\x12\x11\n\tstartDate\x18\x03 \x01(\t\x12\x0f\n\x07\x65ndDate\x18\x04 \x01(\tBh\n:com.huasheng.quant.open.sdk.protobuf.trade.request.futuresB*FuturesQueryHistoryEntrustListRequestProtob\x06proto3'
)




_FUTURESQUERYHISTORYENTRUSTLISTREQUEST = _descriptor.Descriptor(
  name='FuturesQueryHistoryEntrustListRequest',
  full_name='FuturesQueryHistoryEntrustListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pageNo', full_name='FuturesQueryHistoryEntrustListRequest.pageNo', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='FuturesQueryHistoryEntrustListRequest.pageSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='startDate', full_name='FuturesQueryHistoryEntrustListRequest.startDate', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endDate', full_name='FuturesQueryHistoryEntrustListRequest.endDate', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=178,
)

DESCRIPTOR.message_types_by_name['FuturesQueryHistoryEntrustListRequest'] = _FUTURESQUERYHISTORYENTRUSTLISTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FuturesQueryHistoryEntrustListRequest = _reflection.GeneratedProtocolMessageType('FuturesQueryHistoryEntrustListRequest', (_message.Message,), {
  'DESCRIPTOR' : _FUTURESQUERYHISTORYENTRUSTLISTREQUEST,
  '__module__' : 'trade.request.futures.FuturesQueryHistoryEntrustListRequest_pb2'
  # @@protoc_insertion_point(class_scope:FuturesQueryHistoryEntrustListRequest)
  })
_sym_db.RegisterMessage(FuturesQueryHistoryEntrustListRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
