# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/request/futures/FuturesQueryMaxBuySellAmountRequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/request/futures/FuturesQueryMaxBuySellAmountRequest.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n:com.huasheng.quant.open.sdk.protobuf.trade.request.futuresB(FuturesQueryMaxBuySellAmountRequestProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n?trade/request/futures/FuturesQueryMaxBuySellAmountRequest.proto\"8\n#FuturesQueryMaxBuySellAmountRequest\x12\x11\n\tstockCode\x18\x01 \x01(\tBf\n:com.huasheng.quant.open.sdk.protobuf.trade.request.futuresB(FuturesQueryMaxBuySellAmountRequestProtob\x06proto3'
)




_FUTURESQUERYMAXBUYSELLAMOUNTREQUEST = _descriptor.Descriptor(
  name='FuturesQueryMaxBuySellAmountRequest',
  full_name='FuturesQueryMaxBuySellAmountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stockCode', full_name='FuturesQueryMaxBuySellAmountRequest.stockCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['FuturesQueryMaxBuySellAmountRequest'] = _FUTURESQUERYMAXBUYSELLAMOUNTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FuturesQueryMaxBuySellAmountRequest = _reflection.GeneratedProtocolMessageType('FuturesQueryMaxBuySellAmountRequest', (_message.Message,), {
  'DESCRIPTOR' : _FUTURESQUERYMAXBUYSELLAMOUNTREQUEST,
  '__module__' : 'trade.request.futures.FuturesQueryMaxBuySellAmountRequest_pb2'
  # @@protoc_insertion_point(class_scope:FuturesQueryMaxBuySellAmountRequest)
  })
_sym_db.RegisterMessage(FuturesQueryMaxBuySellAmountRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
