# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/request/futures/FuturesQueryHoldsListRequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/request/futures/FuturesQueryHoldsListRequest.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n:com.huasheng.quant.open.sdk.protobuf.trade.request.futuresB!FuturesQueryHoldsListRequestProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n8trade/request/futures/FuturesQueryHoldsListRequest.proto\"\x1e\n\x1c\x46uturesQueryHoldsListRequestB_\n:com.huasheng.quant.open.sdk.protobuf.trade.request.futuresB!FuturesQueryHoldsListRequestProtob\x06proto3'
)




_FUTURESQUERYHOLDSLISTREQUEST = _descriptor.Descriptor(
  name='FuturesQueryHoldsListRequest',
  full_name='FuturesQueryHoldsListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['FuturesQueryHoldsListRequest'] = _FUTURESQUERYHOLDSLISTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FuturesQueryHoldsListRequest = _reflection.GeneratedProtocolMessageType('FuturesQueryHoldsListRequest', (_message.Message,), {
  'DESCRIPTOR' : _FUTURESQUERYHOLDSLISTREQUEST,
  '__module__' : 'trade.request.futures.FuturesQueryHoldsListRequest_pb2'
  # @@protoc_insertion_point(class_scope:FuturesQueryHoldsListRequest)
  })
_sym_db.RegisterMessage(FuturesQueryHoldsListRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
