# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/request/futures/FuturesCancelEntrustRequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/request/futures/FuturesCancelEntrustRequest.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n:com.huasheng.quant.open.sdk.protobuf.trade.request.futuresB FuturesCancelEntrustRequestProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n7trade/request/futures/FuturesCancelEntrustRequest.proto\"C\n\x1b\x46uturesCancelEntrustRequest\x12\x11\n\tentrustId\x18\x01 \x01(\t\x12\x11\n\tstockCode\x18\x02 \x01(\tB^\n:com.huasheng.quant.open.sdk.protobuf.trade.request.futuresB FuturesCancelEntrustRequestProtob\x06proto3'
)




_FUTURESCANCELENTRUSTREQUEST = _descriptor.Descriptor(
  name='FuturesCancelEntrustRequest',
  full_name='FuturesCancelEntrustRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entrustId', full_name='FuturesCancelEntrustRequest.entrustId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stockCode', full_name='FuturesCancelEntrustRequest.stockCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['FuturesCancelEntrustRequest'] = _FUTURESCANCELENTRUSTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FuturesCancelEntrustRequest = _reflection.GeneratedProtocolMessageType('FuturesCancelEntrustRequest', (_message.Message,), {
  'DESCRIPTOR' : _FUTURESCANCELENTRUSTREQUEST,
  '__module__' : 'trade.request.futures.FuturesCancelEntrustRequest_pb2'
  # @@protoc_insertion_point(class_scope:FuturesCancelEntrustRequest)
  })
_sym_db.RegisterMessage(FuturesCancelEntrustRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
