# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hq/dto/FutureBasicQotExData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hq/dto/FutureBasicQotExData.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n2com.huasheng.quant.open.sdk.protobuf.hq.common.dtoB\031FutureBasicQotExDataProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n!hq/dto/FutureBasicQotExData.proto\"F\n\x14\x46utureBasicQotExData\x12\x12\n\nexpiryDate\x18\x01 \x01(\t\x12\x1a\n\x12\x65xpiryDateDistance\x18\x02 \x01(\x05\x42O\n2com.huasheng.quant.open.sdk.protobuf.hq.common.dtoB\x19\x46utureBasicQotExDataProtob\x06proto3'
)




_FUTUREBASICQOTEXDATA = _descriptor.Descriptor(
  name='FutureBasicQotExData',
  full_name='FutureBasicQotExData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='expiryDate', full_name='FutureBasicQotExData.expiryDate', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expiryDateDistance', full_name='FutureBasicQotExData.expiryDateDistance', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['FutureBasicQotExData'] = _FUTUREBASICQOTEXDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FutureBasicQotExData = _reflection.GeneratedProtocolMessageType('FutureBasicQotExData', (_message.Message,), {
  'DESCRIPTOR' : _FUTUREBASICQOTEXDATA,
  '__module__' : 'hq.dto.FutureBasicQotExData_pb2'
  # @@protoc_insertion_point(class_scope:FutureBasicQotExData)
  })
_sym_db.RegisterMessage(FutureBasicQotExData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
