# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plateform/request/OptStockDelRequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='plateform/request/OptStockDelRequest.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n6com.huasheng.quant.open.sdk.protobuf.plateform.requestB\027OptStockDelRequestProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n*plateform/request/OptStockDelRequest.proto\"?\n\x12OptStockDelRequest\x12\x0f\n\x07groupId\x18\x01 \x01(\t\x12\x18\n\x10securityCodeList\x18\x02 \x03(\tBQ\n6com.huasheng.quant.open.sdk.protobuf.plateform.requestB\x17OptStockDelRequestProtob\x06proto3'
)




_OPTSTOCKDELREQUEST = _descriptor.Descriptor(
  name='OptStockDelRequest',
  full_name='OptStockDelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='groupId', full_name='OptStockDelRequest.groupId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='securityCodeList', full_name='OptStockDelRequest.securityCodeList', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['OptStockDelRequest'] = _OPTSTOCKDELREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OptStockDelRequest = _reflection.GeneratedProtocolMessageType('OptStockDelRequest', (_message.Message,), {
  'DESCRIPTOR' : _OPTSTOCKDELREQUEST,
  '__module__' : 'plateform.request.OptStockDelRequest_pb2'
  # @@protoc_insertion_point(class_scope:OptStockDelRequest)
  })
_sym_db.RegisterMessage(OptStockDelRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
