# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/vo/FareVo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/vo/FareVo.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n-com.huasheng.quant.open.sdk.protobuf.trade.voB\013FareVoProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15trade/vo/FareVo.proto\"\x9e\x01\n\x06\x46\x61reVo\x12\r\n\x05\x66\x61re0\x18\x01 \x01(\t\x12\r\n\x05\x66\x61re1\x18\x02 \x01(\t\x12\r\n\x05\x66\x61re2\x18\x03 \x01(\t\x12\r\n\x05\x66\x61re3\x18\x04 \x01(\t\x12\r\n\x05\x66\x61re4\x18\x05 \x01(\t\x12\r\n\x05\x66\x61re5\x18\x06 \x01(\t\x12\r\n\x05\x66\x61re6\x18\x07 \x01(\t\x12\r\n\x05\x66\x61re7\x18\x08 \x01(\t\x12\r\n\x05\x66\x61rex\x18\t \x01(\t\x12\r\n\x05\x66\x61ret\x18\n \x01(\tB<\n-com.huasheng.quant.open.sdk.protobuf.trade.voB\x0b\x46\x61reVoProtob\x06proto3'
)




_FAREVO = _descriptor.Descriptor(
  name='FareVo',
  full_name='FareVo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fare0', full_name='FareVo.fare0', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fare1', full_name='FareVo.fare1', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fare2', full_name='FareVo.fare2', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fare3', full_name='FareVo.fare3', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fare4', full_name='FareVo.fare4', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fare5', full_name='FareVo.fare5', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fare6', full_name='FareVo.fare6', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fare7', full_name='FareVo.fare7', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='farex', full_name='FareVo.farex', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='faret', full_name='FareVo.faret', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=184,
)

DESCRIPTOR.message_types_by_name['FareVo'] = _FAREVO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FareVo = _reflection.GeneratedProtocolMessageType('FareVo', (_message.Message,), {
  'DESCRIPTOR' : _FAREVO,
  '__module__' : 'trade.vo.FareVo_pb2'
  # @@protoc_insertion_point(class_scope:FareVo)
  })
_sym_db.RegisterMessage(FareVo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
