# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/vo/HoldsVo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/vo/HoldsVo.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n-com.huasheng.quant.open.sdk.protobuf.trade.voB\014HoldsVoProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16trade/vo/HoldsVo.proto\"\xd2\x02\n\x07HoldsVo\x12\x11\n\tstockName\x18\x01 \x01(\t\x12\x14\n\x0c\x65nableAmount\x18\x02 \x01(\t\x12\x15\n\rcurrentAmount\x18\x03 \x01(\t\x12\x11\n\tstockCode\x18\x04 \x01(\t\x12\x11\n\tlastPrice\x18\x05 \x01(\t\x12\x15\n\rincomeBalance\x18\x06 \x01(\t\x12\x11\n\tcostPrice\x18\x07 \x01(\t\x12\x13\n\x0bmarketValue\x18\x08 \x01(\t\x12\x17\n\x0fmarketValueRate\x18\t \x01(\t\x12\x13\n\x0bincomeRatio\x18\n \x01(\t\x12\x14\n\x0c\x64\x61yCostPrice\x18\x0b \x01(\t\x12\x17\n\x0f\x64\x61yInComeAmount\x18\x0c \x01(\t\x12\x18\n\x10\x64\x61yOutComeAmount\x18\r \x01(\t\x12\x15\n\rkeepCostPrice\x18\x0e \x01(\t\x12\x14\n\x0c\x65xchangeType\x18\x0f \x01(\tB=\n-com.huasheng.quant.open.sdk.protobuf.trade.voB\x0cHoldsVoProtob\x06proto3'
)




_HOLDSVO = _descriptor.Descriptor(
  name='HoldsVo',
  full_name='HoldsVo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stockName', full_name='HoldsVo.stockName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enableAmount', full_name='HoldsVo.enableAmount', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currentAmount', full_name='HoldsVo.currentAmount', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stockCode', full_name='HoldsVo.stockCode', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lastPrice', full_name='HoldsVo.lastPrice', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='incomeBalance', full_name='HoldsVo.incomeBalance', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='costPrice', full_name='HoldsVo.costPrice', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='marketValue', full_name='HoldsVo.marketValue', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='marketValueRate', full_name='HoldsVo.marketValueRate', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='incomeRatio', full_name='HoldsVo.incomeRatio', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dayCostPrice', full_name='HoldsVo.dayCostPrice', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dayInComeAmount', full_name='HoldsVo.dayInComeAmount', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dayOutComeAmount', full_name='HoldsVo.dayOutComeAmount', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keepCostPrice', full_name='HoldsVo.keepCostPrice', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exchangeType', full_name='HoldsVo.exchangeType', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=365,
)

DESCRIPTOR.message_types_by_name['HoldsVo'] = _HOLDSVO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HoldsVo = _reflection.GeneratedProtocolMessageType('HoldsVo', (_message.Message,), {
  'DESCRIPTOR' : _HOLDSVO,
  '__module__' : 'trade.vo.HoldsVo_pb2'
  # @@protoc_insertion_point(class_scope:HoldsVo)
  })
_sym_db.RegisterMessage(HoldsVo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
