# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/vo/MaxAvailableAssetVo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/vo/MaxAvailableAssetVo.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n-com.huasheng.quant.open.sdk.protobuf.trade.voB\030MaxAvailableAssetVoProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"trade/vo/MaxAvailableAssetVo.proto\"\x8b\x04\n\x13MaxAvailableAssetVo\x12\x16\n\x0epositionStatus\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x02 \x01(\t\x12\x19\n\x11longOpenAvailable\x18\x03 \x01(\t\x12\x1a\n\x12longCloseAvailable\x18\x04 \x01(\t\x12\x1b\n\x13\x63\x61shAvailableToOpen\x18\x05 \x01(\t\x12\x1d\n\x15marginAvailableToOpen\x18\x06 \x01(\t\x12$\n\x1c\x63\x61shAndMarginAvailableToOpen\x18\x07 \x01(\t\x12\x1b\n\x13\x63\x61shAvailableAmount\x18\x08 \x01(\t\x12\x1d\n\x15marginAvailableAmount\x18\t \x01(\t\x12$\n\x1c\x63\x61shAndMarginAvailableAmount\x18\n \x01(\t\x12\x1a\n\x12shortOpenAvailable\x18\x0b \x01(\t\x12\x1b\n\x13shortCloseAvailable\x18\x0c \x01(\t\x12\x1f\n\x17shortCloseCashAvailable\x18\r \x01(\t\x12\x15\n\rshortOpenPool\x18\x0e \x01(\t\x12\x15\n\rshortBuyPower\x18\x0f \x01(\t\x12\x14\n\x0c\x63ontractSize\x18\x10 \x01(\t\x12\x1c\n\x14unitedBuyPowerStatus\x18\x11 \x01(\t\x12\x13\n\x0b\x63reditLimit\x18\x12 \x01(\tBI\n-com.huasheng.quant.open.sdk.protobuf.trade.voB\x18MaxAvailableAssetVoProtob\x06proto3'
)




_MAXAVAILABLEASSETVO = _descriptor.Descriptor(
  name='MaxAvailableAssetVo',
  full_name='MaxAvailableAssetVo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='positionStatus', full_name='MaxAvailableAssetVo.positionStatus', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='MaxAvailableAssetVo.position', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longOpenAvailable', full_name='MaxAvailableAssetVo.longOpenAvailable', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longCloseAvailable', full_name='MaxAvailableAssetVo.longCloseAvailable', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cashAvailableToOpen', full_name='MaxAvailableAssetVo.cashAvailableToOpen', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='marginAvailableToOpen', full_name='MaxAvailableAssetVo.marginAvailableToOpen', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cashAndMarginAvailableToOpen', full_name='MaxAvailableAssetVo.cashAndMarginAvailableToOpen', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cashAvailableAmount', full_name='MaxAvailableAssetVo.cashAvailableAmount', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='marginAvailableAmount', full_name='MaxAvailableAssetVo.marginAvailableAmount', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cashAndMarginAvailableAmount', full_name='MaxAvailableAssetVo.cashAndMarginAvailableAmount', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shortOpenAvailable', full_name='MaxAvailableAssetVo.shortOpenAvailable', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shortCloseAvailable', full_name='MaxAvailableAssetVo.shortCloseAvailable', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shortCloseCashAvailable', full_name='MaxAvailableAssetVo.shortCloseCashAvailable', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shortOpenPool', full_name='MaxAvailableAssetVo.shortOpenPool', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shortBuyPower', full_name='MaxAvailableAssetVo.shortBuyPower', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contractSize', full_name='MaxAvailableAssetVo.contractSize', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unitedBuyPowerStatus', full_name='MaxAvailableAssetVo.unitedBuyPowerStatus', index=16,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='creditLimit', full_name='MaxAvailableAssetVo.creditLimit', index=17,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=562,
)

DESCRIPTOR.message_types_by_name['MaxAvailableAssetVo'] = _MAXAVAILABLEASSETVO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MaxAvailableAssetVo = _reflection.GeneratedProtocolMessageType('MaxAvailableAssetVo', (_message.Message,), {
  'DESCRIPTOR' : _MAXAVAILABLEASSETVO,
  '__module__' : 'trade.vo.MaxAvailableAssetVo_pb2'
  # @@protoc_insertion_point(class_scope:MaxAvailableAssetVo)
  })
_sym_db.RegisterMessage(MaxAvailableAssetVo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
