# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/constant/NotifyMsgType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/constant/NotifyMsgType.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n4com.huasheng.quant.open.sdk.protobuf.common.constantB\022NotifyMsgTypeProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#common/constant/NotifyMsgType.proto*\xe4\x01\n\rNotifyMsgType\x12\x1a\n\x16TrsStockDeliverMsgType\x10\x00\x12\x1c\n\x18TradeStockDeliverMsgType\x10\x01\x12#\n\x1f\x46uturesTradeStockDeliverMsgType\x10\x02\x12\x1c\n\x16OrderBookNotifyMsgType\x10\xa1\x9c\x01\x12\x1e\n\x18\x42rokerQueueNotifyMsgType\x10\xa2\x9c\x01\x12\x1b\n\x15\x42\x61sicQotNotifyMsgType\x10\xa3\x9c\x01\x12\x19\n\x13TickerNotifyMsgType\x10\xa4\x9c\x01\x42J\n4com.huasheng.quant.open.sdk.protobuf.common.constantB\x12NotifyMsgTypeProtob\x06proto3'
)

_NOTIFYMSGTYPE = _descriptor.EnumDescriptor(
  name='NotifyMsgType',
  full_name='NotifyMsgType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TrsStockDeliverMsgType', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TradeStockDeliverMsgType', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FuturesTradeStockDeliverMsgType', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OrderBookNotifyMsgType', index=3, number=20001,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BrokerQueueNotifyMsgType', index=4, number=20002,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BasicQotNotifyMsgType', index=5, number=20003,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TickerNotifyMsgType', index=6, number=20004,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=40,
  serialized_end=268,
)
_sym_db.RegisterEnumDescriptor(_NOTIFYMSGTYPE)

NotifyMsgType = enum_type_wrapper.EnumTypeWrapper(_NOTIFYMSGTYPE)
TrsStockDeliverMsgType = 0
TradeStockDeliverMsgType = 1
FuturesTradeStockDeliverMsgType = 2
OrderBookNotifyMsgType = 20001
BrokerQueueNotifyMsgType = 20002
BasicQotNotifyMsgType = 20003
TickerNotifyMsgType = 20004


DESCRIPTOR.enum_types_by_name['NotifyMsgType'] = _NOTIFYMSGTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
