# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/request/TradeQueryRealCondOrderListRequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/request/TradeQueryRealCondOrderListRequest.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n2com.huasheng.quant.open.sdk.protobuf.trade.requestB\'TradeQueryRealCondOrderListRequestProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n6trade/request/TradeQueryRealCondOrderListRequest.proto\"o\n\"TradeQueryRealCondOrderListRequest\x12\x14\n\x0c\x65xchangeType\x18\x01 \x01(\t\x12\x11\n\tstockCode\x18\x02 \x01(\t\x12\x0e\n\x06pageNo\x18\x03 \x01(\x05\x12\x10\n\x08pageSize\x18\x04 \x01(\x05\x42]\n2com.huasheng.quant.open.sdk.protobuf.trade.requestB\'TradeQueryRealCondOrderListRequestProtob\x06proto3'
)




_TRADEQUERYREALCONDORDERLISTREQUEST = _descriptor.Descriptor(
  name='TradeQueryRealCondOrderListRequest',
  full_name='TradeQueryRealCondOrderListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchangeType', full_name='TradeQueryRealCondOrderListRequest.exchangeType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stockCode', full_name='TradeQueryRealCondOrderListRequest.stockCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pageNo', full_name='TradeQueryRealCondOrderListRequest.pageNo', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='TradeQueryRealCondOrderListRequest.pageSize', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=169,
)

DESCRIPTOR.message_types_by_name['TradeQueryRealCondOrderListRequest'] = _TRADEQUERYREALCONDORDERLISTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TradeQueryRealCondOrderListRequest = _reflection.GeneratedProtocolMessageType('TradeQueryRealCondOrderListRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRADEQUERYREALCONDORDERLISTREQUEST,
  '__module__' : 'trade.request.TradeQueryRealCondOrderListRequest_pb2'
  # @@protoc_insertion_point(class_scope:TradeQueryRealCondOrderListRequest)
  })
_sym_db.RegisterMessage(TradeQueryRealCondOrderListRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
