# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/request/TradeLoginRequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/request/TradeLoginRequest.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n2com.huasheng.quant.open.sdk.protobuf.trade.requestB\026TradeLoginRequestProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n%trade/request/TradeLoginRequest.proto\"J\n\x11TradeLoginRequest\x12\x10\n\x08password\x18\x01 \x01(\t\x12\x10\n\x08\x61uthType\x18\x02 \x01(\t\x12\x11\n\tauthParam\x18\x03 \x01(\tBL\n2com.huasheng.quant.open.sdk.protobuf.trade.requestB\x16TradeLoginRequestProtob\x06proto3'
)




_TRADELOGINREQUEST = _descriptor.Descriptor(
  name='TradeLoginRequest',
  full_name='TradeLoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='password', full_name='TradeLoginRequest.password', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='authType', full_name='TradeLoginRequest.authType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='authParam', full_name='TradeLoginRequest.authParam', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['TradeLoginRequest'] = _TRADELOGINREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TradeLoginRequest = _reflection.GeneratedProtocolMessageType('TradeLoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRADELOGINREQUEST,
  '__module__' : 'trade.request.TradeLoginRequest_pb2'
  # @@protoc_insertion_point(class_scope:TradeLoginRequest)
  })
_sym_db.RegisterMessage(TradeLoginRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
