# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/request/TradeQueryHistoryCondOrderListRequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/request/TradeQueryHistoryCondOrderListRequest.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n2com.huasheng.quant.open.sdk.protobuf.trade.requestB*TradeQueryHistoryCondOrderListRequestProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n9trade/request/TradeQueryHistoryCondOrderListRequest.proto\"\x96\x01\n%TradeQueryHistoryCondOrderListRequest\x12\x14\n\x0c\x65xchangeType\x18\x01 \x01(\t\x12\x11\n\tstockCode\x18\x02 \x01(\t\x12\x0e\n\x06pageNo\x18\x03 \x01(\x05\x12\x10\n\x08pageSize\x18\x04 \x01(\x05\x12\x11\n\tstartTime\x18\x05 \x01(\t\x12\x0f\n\x07\x65ndTime\x18\x06 \x01(\tB`\n2com.huasheng.quant.open.sdk.protobuf.trade.requestB*TradeQueryHistoryCondOrderListRequestProtob\x06proto3'
)




_TRADEQUERYHISTORYCONDORDERLISTREQUEST = _descriptor.Descriptor(
  name='TradeQueryHistoryCondOrderListRequest',
  full_name='TradeQueryHistoryCondOrderListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchangeType', full_name='TradeQueryHistoryCondOrderListRequest.exchangeType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stockCode', full_name='TradeQueryHistoryCondOrderListRequest.stockCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pageNo', full_name='TradeQueryHistoryCondOrderListRequest.pageNo', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='TradeQueryHistoryCondOrderListRequest.pageSize', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='startTime', full_name='TradeQueryHistoryCondOrderListRequest.startTime', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endTime', full_name='TradeQueryHistoryCondOrderListRequest.endTime', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=212,
)

DESCRIPTOR.message_types_by_name['TradeQueryHistoryCondOrderListRequest'] = _TRADEQUERYHISTORYCONDORDERLISTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TradeQueryHistoryCondOrderListRequest = _reflection.GeneratedProtocolMessageType('TradeQueryHistoryCondOrderListRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRADEQUERYHISTORYCONDORDERLISTREQUEST,
  '__module__' : 'trade.request.TradeQueryHistoryCondOrderListRequest_pb2'
  # @@protoc_insertion_point(class_scope:TradeQueryHistoryCondOrderListRequest)
  })
_sym_db.RegisterMessage(TradeQueryHistoryCondOrderListRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
