# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/request/TradeQueryHoldsListRequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/request/TradeQueryHoldsListRequest.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n2com.huasheng.quant.open.sdk.protobuf.trade.requestB\037TradeQueryHoldsListRequestProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n.trade/request/TradeQueryHoldsListRequest.proto\"2\n\x1aTradeQueryHoldsListRequest\x12\x14\n\x0c\x65xchangeType\x18\x01 \x01(\tBU\n2com.huasheng.quant.open.sdk.protobuf.trade.requestB\x1fTradeQueryHoldsListRequestProtob\x06proto3'
)




_TRADEQUERYHOLDSLISTREQUEST = _descriptor.Descriptor(
  name='TradeQueryHoldsListRequest',
  full_name='TradeQueryHoldsListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchangeType', full_name='TradeQueryHoldsListRequest.exchangeType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['TradeQueryHoldsListRequest'] = _TRADEQUERYHOLDSLISTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TradeQueryHoldsListRequest = _reflection.GeneratedProtocolMessageType('TradeQueryHoldsListRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRADEQUERYHOLDSLISTREQUEST,
  '__module__' : 'trade.request.TradeQueryHoldsListRequest_pb2'
  # @@protoc_insertion_point(class_scope:TradeQueryHoldsListRequest)
  })
_sym_db.RegisterMessage(TradeQueryHoldsListRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
