# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/response/futures/FuturesQueryHistoryDeliverListResponse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hs.common.pb.trade.vo.futures import FuturesOrderVo_pb2 as trade_dot_vo_dot_futures_dot_FuturesOrderVo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/response/futures/FuturesQueryHistoryDeliverListResponse.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n;com.huasheng.quant.open.sdk.protobuf.trade.response.futuresB+FuturesQueryHistoryDeliverListResponseProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nCtrade/response/futures/FuturesQueryHistoryDeliverListResponse.proto\x1a%trade/vo/futures/FuturesOrderVo.proto\"\x96\x01\n&FuturesQueryHistoryDeliverListResponse\x12\x1d\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0f.FuturesOrderVo\x12\x11\n\tcurPageNo\x18\x02 \x01(\x05\x12\x13\n\x0b\x63urPageSize\x18\x03 \x01(\x05\x12\x13\n\x0btotalPageNo\x18\x04 \x01(\x05\x12\x10\n\x08lastPage\x18\x05 \x01(\x05\x42j\n;com.huasheng.quant.open.sdk.protobuf.trade.response.futuresB+FuturesQueryHistoryDeliverListResponseProtob\x06proto3'
  ,
  dependencies=[trade_dot_vo_dot_futures_dot_FuturesOrderVo__pb2.DESCRIPTOR,])




_FUTURESQUERYHISTORYDELIVERLISTRESPONSE = _descriptor.Descriptor(
  name='FuturesQueryHistoryDeliverListResponse',
  full_name='FuturesQueryHistoryDeliverListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='FuturesQueryHistoryDeliverListResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='curPageNo', full_name='FuturesQueryHistoryDeliverListResponse.curPageNo', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='curPageSize', full_name='FuturesQueryHistoryDeliverListResponse.curPageSize', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='totalPageNo', full_name='FuturesQueryHistoryDeliverListResponse.totalPageNo', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lastPage', full_name='FuturesQueryHistoryDeliverListResponse.lastPage', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=261,
)

_FUTURESQUERYHISTORYDELIVERLISTRESPONSE.fields_by_name['data'].message_type = trade_dot_vo_dot_futures_dot_FuturesOrderVo__pb2._FUTURESORDERVO
DESCRIPTOR.message_types_by_name['FuturesQueryHistoryDeliverListResponse'] = _FUTURESQUERYHISTORYDELIVERLISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FuturesQueryHistoryDeliverListResponse = _reflection.GeneratedProtocolMessageType('FuturesQueryHistoryDeliverListResponse', (_message.Message,), {
  'DESCRIPTOR' : _FUTURESQUERYHISTORYDELIVERLISTRESPONSE,
  '__module__' : 'trade.response.futures.FuturesQueryHistoryDeliverListResponse_pb2'
  # @@protoc_insertion_point(class_scope:FuturesQueryHistoryDeliverListResponse)
  })
_sym_db.RegisterMessage(FuturesQueryHistoryDeliverListResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
