# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/response/futures/FuturesQueryRealDeliverListResponse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hs.common.pb.trade.vo.futures import FuturesOrderVo_pb2 as trade_dot_vo_dot_futures_dot_FuturesOrderVo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/response/futures/FuturesQueryRealDeliverListResponse.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n;com.huasheng.quant.open.sdk.protobuf.trade.response.futuresB(FuturesQueryRealDeliverListResponseProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n@trade/response/futures/FuturesQueryRealDeliverListResponse.proto\x1a%trade/vo/futures/FuturesOrderVo.proto\"D\n#FuturesQueryRealDeliverListResponse\x12\x1d\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0f.FuturesOrderVoBg\n;com.huasheng.quant.open.sdk.protobuf.trade.response.futuresB(FuturesQueryRealDeliverListResponseProtob\x06proto3'
  ,
  dependencies=[trade_dot_vo_dot_futures_dot_FuturesOrderVo__pb2.DESCRIPTOR,])




_FUTURESQUERYREALDELIVERLISTRESPONSE = _descriptor.Descriptor(
  name='FuturesQueryRealDeliverListResponse',
  full_name='FuturesQueryRealDeliverListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='FuturesQueryRealDeliverListResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=175,
)

_FUTURESQUERYREALDELIVERLISTRESPONSE.fields_by_name['data'].message_type = trade_dot_vo_dot_futures_dot_FuturesOrderVo__pb2._FUTURESORDERVO
DESCRIPTOR.message_types_by_name['FuturesQueryRealDeliverListResponse'] = _FUTURESQUERYREALDELIVERLISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FuturesQueryRealDeliverListResponse = _reflection.GeneratedProtocolMessageType('FuturesQueryRealDeliverListResponse', (_message.Message,), {
  'DESCRIPTOR' : _FUTURESQUERYREALDELIVERLISTRESPONSE,
  '__module__' : 'trade.response.futures.FuturesQueryRealDeliverListResponse_pb2'
  # @@protoc_insertion_point(class_scope:FuturesQueryRealDeliverListResponse)
  })
_sym_db.RegisterMessage(FuturesQueryRealDeliverListResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
