# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/response/futures/FuturesQueryBuySellAmountResponse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/response/futures/FuturesQueryBuySellAmountResponse.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n;com.huasheng.quant.open.sdk.protobuf.trade.response.futuresB&FuturesQueryBuySellAmountResponseProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n>trade/response/futures/FuturesQueryBuySellAmountResponse.proto\"\x8c\x01\n!FuturesQueryBuySellAmountResponse\x12\x16\n\x0epositionStatus\x18\x01 \x01(\x05\x12\x14\n\x0cmaxBuyAmount\x18\x02 \x01(\x03\x12\x15\n\rmaxSellAmount\x18\x03 \x01(\x03\x12\x15\n\rinitialMargin\x18\x04 \x01(\t\x12\x0b\n\x03\x63\x63y\x18\x05 \x01(\tBe\n;com.huasheng.quant.open.sdk.protobuf.trade.response.futuresB&FuturesQueryBuySellAmountResponseProtob\x06proto3'
)




_FUTURESQUERYBUYSELLAMOUNTRESPONSE = _descriptor.Descriptor(
  name='FuturesQueryBuySellAmountResponse',
  full_name='FuturesQueryBuySellAmountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='positionStatus', full_name='FuturesQueryBuySellAmountResponse.positionStatus', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maxBuyAmount', full_name='FuturesQueryBuySellAmountResponse.maxBuyAmount', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maxSellAmount', full_name='FuturesQueryBuySellAmountResponse.maxSellAmount', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='initialMargin', full_name='FuturesQueryBuySellAmountResponse.initialMargin', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ccy', full_name='FuturesQueryBuySellAmountResponse.ccy', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=207,
)

DESCRIPTOR.message_types_by_name['FuturesQueryBuySellAmountResponse'] = _FUTURESQUERYBUYSELLAMOUNTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FuturesQueryBuySellAmountResponse = _reflection.GeneratedProtocolMessageType('FuturesQueryBuySellAmountResponse', (_message.Message,), {
  'DESCRIPTOR' : _FUTURESQUERYBUYSELLAMOUNTRESPONSE,
  '__module__' : 'trade.response.futures.FuturesQueryBuySellAmountResponse_pb2'
  # @@protoc_insertion_point(class_scope:FuturesQueryBuySellAmountResponse)
  })
_sym_db.RegisterMessage(FuturesQueryBuySellAmountResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
