# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/response/futures/FuturesQueryHoldsListResponse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hs.common.pb.trade.vo.futures import FuturesFundInfoVo_pb2 as trade_dot_vo_dot_futures_dot_FuturesFundInfoVo__pb2
from hs.common.pb.trade.vo.futures import FuturesHoldsVo_pb2 as trade_dot_vo_dot_futures_dot_FuturesHoldsVo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/response/futures/FuturesQueryHoldsListResponse.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n;com.huasheng.quant.open.sdk.protobuf.trade.response.futuresB\"FuturesQueryHoldsListResponseProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n:trade/response/futures/FuturesQueryHoldsListResponse.proto\x1a(trade/vo/futures/FuturesFundInfoVo.proto\x1a%trade/vo/futures/FuturesHoldsVo.proto\"i\n\x1d\x46uturesQueryHoldsListResponse\x12$\n\x08\x66undInfo\x18\x01 \x01(\x0b\x32\x12.FuturesFundInfoVo\x12\"\n\tholdsList\x18\x02 \x03(\x0b\x32\x0f.FuturesHoldsVoBa\n;com.huasheng.quant.open.sdk.protobuf.trade.response.futuresB\"FuturesQueryHoldsListResponseProtob\x06proto3'
  ,
  dependencies=[trade_dot_vo_dot_futures_dot_FuturesFundInfoVo__pb2.DESCRIPTOR,trade_dot_vo_dot_futures_dot_FuturesHoldsVo__pb2.DESCRIPTOR,])




_FUTURESQUERYHOLDSLISTRESPONSE = _descriptor.Descriptor(
  name='FuturesQueryHoldsListResponse',
  full_name='FuturesQueryHoldsListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fundInfo', full_name='FuturesQueryHoldsListResponse.fundInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='holdsList', full_name='FuturesQueryHoldsListResponse.holdsList', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=248,
)

_FUTURESQUERYHOLDSLISTRESPONSE.fields_by_name['fundInfo'].message_type = trade_dot_vo_dot_futures_dot_FuturesFundInfoVo__pb2._FUTURESFUNDINFOVO
_FUTURESQUERYHOLDSLISTRESPONSE.fields_by_name['holdsList'].message_type = trade_dot_vo_dot_futures_dot_FuturesHoldsVo__pb2._FUTURESHOLDSVO
DESCRIPTOR.message_types_by_name['FuturesQueryHoldsListResponse'] = _FUTURESQUERYHOLDSLISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FuturesQueryHoldsListResponse = _reflection.GeneratedProtocolMessageType('FuturesQueryHoldsListResponse', (_message.Message,), {
  'DESCRIPTOR' : _FUTURESQUERYHOLDSLISTRESPONSE,
  '__module__' : 'trade.response.futures.FuturesQueryHoldsListResponse_pb2'
  # @@protoc_insertion_point(class_scope:FuturesQueryHoldsListResponse)
  })
_sym_db.RegisterMessage(FuturesQueryHoldsListResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
