# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/response/StockQueryHoldsListResponse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hs.common.pb.trade.vo import HoldsVo_pb2 as trade_dot_vo_dot_HoldsVo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/response/StockQueryHoldsListResponse.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n3com.huasheng.quant.open.sdk.protobuf.trade.responseB StockQueryHoldsListResponseProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n0trade/response/StockQueryHoldsListResponse.proto\x1a\x16trade/vo/HoldsVo.proto\":\n\x1bStockQueryHoldsListResponse\x12\x1b\n\tholdsList\x18\x01 \x03(\x0b\x32\x08.HoldsVoBW\n3com.huasheng.quant.open.sdk.protobuf.trade.responseB StockQueryHoldsListResponseProtob\x06proto3'
  ,
  dependencies=[trade_dot_vo_dot_HoldsVo__pb2.DESCRIPTOR,])




_STOCKQUERYHOLDSLISTRESPONSE = _descriptor.Descriptor(
  name='StockQueryHoldsListResponse',
  full_name='StockQueryHoldsListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='holdsList', full_name='StockQueryHoldsListResponse.holdsList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=134,
)

_STOCKQUERYHOLDSLISTRESPONSE.fields_by_name['holdsList'].message_type = trade_dot_vo_dot_HoldsVo__pb2._HOLDSVO
DESCRIPTOR.message_types_by_name['StockQueryHoldsListResponse'] = _STOCKQUERYHOLDSLISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StockQueryHoldsListResponse = _reflection.GeneratedProtocolMessageType('StockQueryHoldsListResponse', (_message.Message,), {
  'DESCRIPTOR' : _STOCKQUERYHOLDSLISTRESPONSE,
  '__module__' : 'trade.response.StockQueryHoldsListResponse_pb2'
  # @@protoc_insertion_point(class_scope:StockQueryHoldsListResponse)
  })
_sym_db.RegisterMessage(StockQueryHoldsListResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
