# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/response/TradeQueryHistoryFundJourListResponse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hs.common.pb.trade.vo import FundJourVo_pb2 as trade_dot_vo_dot_FundJourVo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/response/TradeQueryHistoryFundJourListResponse.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n3com.huasheng.quant.open.sdk.protobuf.trade.responseB*TradeQueryHistoryFundJourListResponseProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n:trade/response/TradeQueryHistoryFundJourListResponse.proto\x1a\x19trade/vo/FundJourVo.proto\"B\n%TradeQueryHistoryFundJourListResponse\x12\x19\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0b.FundJourVoBa\n3com.huasheng.quant.open.sdk.protobuf.trade.responseB*TradeQueryHistoryFundJourListResponseProtob\x06proto3'
  ,
  dependencies=[trade_dot_vo_dot_FundJourVo__pb2.DESCRIPTOR,])




_TRADEQUERYHISTORYFUNDJOURLISTRESPONSE = _descriptor.Descriptor(
  name='TradeQueryHistoryFundJourListResponse',
  full_name='TradeQueryHistoryFundJourListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='TradeQueryHistoryFundJourListResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=155,
)

_TRADEQUERYHISTORYFUNDJOURLISTRESPONSE.fields_by_name['data'].message_type = trade_dot_vo_dot_FundJourVo__pb2._FUNDJOURVO
DESCRIPTOR.message_types_by_name['TradeQueryHistoryFundJourListResponse'] = _TRADEQUERYHISTORYFUNDJOURLISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TradeQueryHistoryFundJourListResponse = _reflection.GeneratedProtocolMessageType('TradeQueryHistoryFundJourListResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRADEQUERYHISTORYFUNDJOURLISTRESPONSE,
  '__module__' : 'trade.response.TradeQueryHistoryFundJourListResponse_pb2'
  # @@protoc_insertion_point(class_scope:TradeQueryHistoryFundJourListResponse)
  })
_sym_db.RegisterMessage(TradeQueryHistoryFundJourListResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
