# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/response/TradeQueryMarginFundInfoResponse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/response/TradeQueryMarginFundInfoResponse.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n3com.huasheng.quant.open.sdk.protobuf.trade.responseB%TradeQueryMarginFundInfoResponseProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n5trade/response/TradeQueryMarginFundInfoResponse.proto\"\xab\x05\n TradeQueryMarginFundInfoResponse\x12\x14\n\x0choldsBalance\x18\x01 \x01(\t\x12\x14\n\x0c\x61ssetBalance\x18\x02 \x01(\t\x12\x15\n\renableBalance\x18\x03 \x01(\t\x12\x13\n\x0bmarketValue\x18\x04 \x01(\t\x12\x12\n\ncashOnHold\x18\x05 \x01(\t\x12\x13\n\x0b\x63reditValue\x18\x06 \x01(\t\x12\x12\n\ncreditLine\x18\x07 \x01(\t\x12\x14\n\x0c\x66\x65tchBalance\x18\x08 \x01(\t\x12\x15\n\rfrozenBalance\x18\t \x01(\t\x12\x15\n\raccountStatus\x18\n \x01(\t\x12\x12\n\nspentRatio\x18\x0b \x01(\t\x12\x1a\n\x12\x63urrentCreditLimit\x18\x1e \x01(\t\x12\x16\n\x0emaxCreditLimit\x18\x1f \x01(\t\x12\x17\n\x0funitCreditLimit\x18  \x01(\t\x12\x1a\n\x12unitMaxCreditLimit\x18! \x01(\t\x12\x10\n\x08\x62uyPower\x18( \x01(\t\x12\x16\n\x0e\x62uyPowerCredit\x18) \x01(\t\x12\x12\n\nbuyPowerHk\x18* \x01(\t\x12\x12\n\nbuyPowerUs\x18+ \x01(\t\x12\x12\n\nbuyPowerCn\x18, \x01(\t\x12\x18\n\x10unitedBuyPowerHk\x18- \x01(\t\x12\x18\n\x10unitedBuyPowerUs\x18. \x01(\t\x12\x18\n\x10unitedBuyPowerCn\x18/ \x01(\t\x12\x17\n\x0fthirdBuyPowerHk\x18\x30 \x01(\t\x12\x17\n\x0fthirdBuyPowerUs\x18\x31 \x01(\t\x12\x17\n\x0fthirdBuyPowerCn\x18\x32 \x01(\t\x12\x1b\n\x13\x62uyPowerShortMarket\x18\x33 \x01(\t\x12\x15\n\rbuyPowerMoney\x18\x34 \x01(\tB\\\n3com.huasheng.quant.open.sdk.protobuf.trade.responseB%TradeQueryMarginFundInfoResponseProtob\x06proto3'
)




_TRADEQUERYMARGINFUNDINFORESPONSE = _descriptor.Descriptor(
  name='TradeQueryMarginFundInfoResponse',
  full_name='TradeQueryMarginFundInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='holdsBalance', full_name='TradeQueryMarginFundInfoResponse.holdsBalance', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='assetBalance', full_name='TradeQueryMarginFundInfoResponse.assetBalance', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enableBalance', full_name='TradeQueryMarginFundInfoResponse.enableBalance', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='marketValue', full_name='TradeQueryMarginFundInfoResponse.marketValue', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cashOnHold', full_name='TradeQueryMarginFundInfoResponse.cashOnHold', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='creditValue', full_name='TradeQueryMarginFundInfoResponse.creditValue', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='creditLine', full_name='TradeQueryMarginFundInfoResponse.creditLine', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fetchBalance', full_name='TradeQueryMarginFundInfoResponse.fetchBalance', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frozenBalance', full_name='TradeQueryMarginFundInfoResponse.frozenBalance', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accountStatus', full_name='TradeQueryMarginFundInfoResponse.accountStatus', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='spentRatio', full_name='TradeQueryMarginFundInfoResponse.spentRatio', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='currentCreditLimit', full_name='TradeQueryMarginFundInfoResponse.currentCreditLimit', index=11,
      number=30, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maxCreditLimit', full_name='TradeQueryMarginFundInfoResponse.maxCreditLimit', index=12,
      number=31, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unitCreditLimit', full_name='TradeQueryMarginFundInfoResponse.unitCreditLimit', index=13,
      number=32, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unitMaxCreditLimit', full_name='TradeQueryMarginFundInfoResponse.unitMaxCreditLimit', index=14,
      number=33, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buyPower', full_name='TradeQueryMarginFundInfoResponse.buyPower', index=15,
      number=40, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buyPowerCredit', full_name='TradeQueryMarginFundInfoResponse.buyPowerCredit', index=16,
      number=41, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buyPowerHk', full_name='TradeQueryMarginFundInfoResponse.buyPowerHk', index=17,
      number=42, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buyPowerUs', full_name='TradeQueryMarginFundInfoResponse.buyPowerUs', index=18,
      number=43, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buyPowerCn', full_name='TradeQueryMarginFundInfoResponse.buyPowerCn', index=19,
      number=44, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unitedBuyPowerHk', full_name='TradeQueryMarginFundInfoResponse.unitedBuyPowerHk', index=20,
      number=45, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unitedBuyPowerUs', full_name='TradeQueryMarginFundInfoResponse.unitedBuyPowerUs', index=21,
      number=46, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unitedBuyPowerCn', full_name='TradeQueryMarginFundInfoResponse.unitedBuyPowerCn', index=22,
      number=47, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='thirdBuyPowerHk', full_name='TradeQueryMarginFundInfoResponse.thirdBuyPowerHk', index=23,
      number=48, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='thirdBuyPowerUs', full_name='TradeQueryMarginFundInfoResponse.thirdBuyPowerUs', index=24,
      number=49, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='thirdBuyPowerCn', full_name='TradeQueryMarginFundInfoResponse.thirdBuyPowerCn', index=25,
      number=50, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buyPowerShortMarket', full_name='TradeQueryMarginFundInfoResponse.buyPowerShortMarket', index=26,
      number=51, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='buyPowerMoney', full_name='TradeQueryMarginFundInfoResponse.buyPowerMoney', index=27,
      number=52, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=741,
)

DESCRIPTOR.message_types_by_name['TradeQueryMarginFundInfoResponse'] = _TRADEQUERYMARGINFUNDINFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TradeQueryMarginFundInfoResponse = _reflection.GeneratedProtocolMessageType('TradeQueryMarginFundInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRADEQUERYMARGINFUNDINFORESPONSE,
  '__module__' : 'trade.response.TradeQueryMarginFundInfoResponse_pb2'
  # @@protoc_insertion_point(class_scope:TradeQueryMarginFundInfoResponse)
  })
_sym_db.RegisterMessage(TradeQueryMarginFundInfoResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
