# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/response/TradeQueryStockShortInfoResponse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/response/TradeQueryStockShortInfoResponse.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n3com.huasheng.quant.open.sdk.protobuf.trade.responseB%TradeQueryStockShortInfoResponseProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n5trade/response/TradeQueryStockShortInfoResponse.proto\"N\n TradeQueryStockShortInfoResponse\x12\x14\n\x0csupportShort\x18\x01 \x01(\t\x12\x14\n\x0cinterestRate\x18\x02 \x01(\tB\\\n3com.huasheng.quant.open.sdk.protobuf.trade.responseB%TradeQueryStockShortInfoResponseProtob\x06proto3'
)




_TRADEQUERYSTOCKSHORTINFORESPONSE = _descriptor.Descriptor(
  name='TradeQueryStockShortInfoResponse',
  full_name='TradeQueryStockShortInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='supportShort', full_name='TradeQueryStockShortInfoResponse.supportShort', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='interestRate', full_name='TradeQueryStockShortInfoResponse.interestRate', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=135,
)

DESCRIPTOR.message_types_by_name['TradeQueryStockShortInfoResponse'] = _TRADEQUERYSTOCKSHORTINFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TradeQueryStockShortInfoResponse = _reflection.GeneratedProtocolMessageType('TradeQueryStockShortInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRADEQUERYSTOCKSHORTINFORESPONSE,
  '__module__' : 'trade.response.TradeQueryStockShortInfoResponse_pb2'
  # @@protoc_insertion_point(class_scope:TradeQueryStockShortInfoResponse)
  })
_sym_db.RegisterMessage(TradeQueryStockShortInfoResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
