# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade/response/TradeQueryMaxAvailableAssetResponse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hs.common.pb.trade.vo import MaxAvailableAssetVo_pb2 as trade_dot_vo_dot_MaxAvailableAssetVo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade/response/TradeQueryMaxAvailableAssetResponse.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n3com.huasheng.quant.open.sdk.protobuf.trade.responseB(TradeQueryMaxAvailableAssetResponseProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n8trade/response/TradeQueryMaxAvailableAssetResponse.proto\x1a\"trade/vo/MaxAvailableAssetVo.proto\"I\n#TradeQueryMaxAvailableAssetResponse\x12\"\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x14.MaxAvailableAssetVoB_\n3com.huasheng.quant.open.sdk.protobuf.trade.responseB(TradeQueryMaxAvailableAssetResponseProtob\x06proto3'
  ,
  dependencies=[trade_dot_vo_dot_MaxAvailableAssetVo__pb2.DESCRIPTOR,])




_TRADEQUERYMAXAVAILABLEASSETRESPONSE = _descriptor.Descriptor(
  name='TradeQueryMaxAvailableAssetResponse',
  full_name='TradeQueryMaxAvailableAssetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='TradeQueryMaxAvailableAssetResponse.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=169,
)

_TRADEQUERYMAXAVAILABLEASSETRESPONSE.fields_by_name['data'].message_type = trade_dot_vo_dot_MaxAvailableAssetVo__pb2._MAXAVAILABLEASSETVO
DESCRIPTOR.message_types_by_name['TradeQueryMaxAvailableAssetResponse'] = _TRADEQUERYMAXAVAILABLEASSETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TradeQueryMaxAvailableAssetResponse = _reflection.GeneratedProtocolMessageType('TradeQueryMaxAvailableAssetResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRADEQUERYMAXAVAILABLEASSETRESPONSE,
  '__module__' : 'trade.response.TradeQueryMaxAvailableAssetResponse_pb2'
  # @@protoc_insertion_point(class_scope:TradeQueryMaxAvailableAssetResponse)
  })
_sym_db.RegisterMessage(TradeQueryMaxAvailableAssetResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
