# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plateform/response/OptStockGroupQueryResponse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hs.common.pb.plateform.vo import MemberOptStockGroup_pb2 as plateform_dot_vo_dot_MemberOptStockGroup__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='plateform/response/OptStockGroupQueryResponse.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n7com.huasheng.quant.open.sdk.protobuf.plateform.responseB\037OptStockGroupQueryResponseProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n3plateform/response/OptStockGroupQueryResponse.proto\x1a&plateform/vo/MemberOptStockGroup.proto\"A\n\x1aOptStockGroupQueryResponse\x12#\n\x05group\x18\x01 \x03(\x0b\x32\x14.MemberOptStockGroupBZ\n7com.huasheng.quant.open.sdk.protobuf.plateform.responseB\x1fOptStockGroupQueryResponseProtob\x06proto3'
  ,
  dependencies=[plateform_dot_vo_dot_MemberOptStockGroup__pb2.DESCRIPTOR,])




_OPTSTOCKGROUPQUERYRESPONSE = _descriptor.Descriptor(
  name='OptStockGroupQueryResponse',
  full_name='OptStockGroupQueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='OptStockGroupQueryResponse.group', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=160,
)

_OPTSTOCKGROUPQUERYRESPONSE.fields_by_name['group'].message_type = plateform_dot_vo_dot_MemberOptStockGroup__pb2._MEMBEROPTSTOCKGROUP
DESCRIPTOR.message_types_by_name['OptStockGroupQueryResponse'] = _OPTSTOCKGROUPQUERYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OptStockGroupQueryResponse = _reflection.GeneratedProtocolMessageType('OptStockGroupQueryResponse', (_message.Message,), {
  'DESCRIPTOR' : _OPTSTOCKGROUPQUERYRESPONSE,
  '__module__' : 'plateform.response.OptStockGroupQueryResponse_pb2'
  # @@protoc_insertion_point(class_scope:OptStockGroupQueryResponse)
  })
_sym_db.RegisterMessage(OptStockGroupQueryResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
