# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hq/request/subscriber/PushsubscribeRequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hs.common.pb.hq.dto import Security_pb2 as hq_dot_dto_dot_Security__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hq/request/subscriber/PushsubscribeRequest.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n:com.huasheng.quant.open.sdk.protobuf.hq.request.subscriberB\031PushsubscribeRequestProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n0hq/request/subscriber/PushsubscribeRequest.proto\x1a\x15hq/dto/Security.proto\"D\n\x14PushsubscribeRequest\x12\x0f\n\x07topicId\x18\x01 \x01(\x05\x12\x1b\n\x08security\x18\x02 \x03(\x0b\x32\t.SecurityBW\n:com.huasheng.quant.open.sdk.protobuf.hq.request.subscriberB\x19PushsubscribeRequestProtob\x06proto3'
  ,
  dependencies=[hq_dot_dto_dot_Security__pb2.DESCRIPTOR,])




_PUSHSUBSCRIBEREQUEST = _descriptor.Descriptor(
  name='PushsubscribeRequest',
  full_name='PushsubscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topicId', full_name='PushsubscribeRequest.topicId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='security', full_name='PushsubscribeRequest.security', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=143,
)

_PUSHSUBSCRIBEREQUEST.fields_by_name['security'].message_type = hq_dot_dto_dot_Security__pb2._SECURITY
DESCRIPTOR.message_types_by_name['PushsubscribeRequest'] = _PUSHSUBSCRIBEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PushsubscribeRequest = _reflection.GeneratedProtocolMessageType('PushsubscribeRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUSHSUBSCRIBEREQUEST,
  '__module__' : 'hq.request.subscriber.PushsubscribeRequest_pb2'
  # @@protoc_insertion_point(class_scope:PushsubscribeRequest)
  })
_sym_db.RegisterMessage(PushsubscribeRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
