# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hq/notify/OrderBookFullNotify.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hs.common.pb.hq.dto import Security_pb2 as hq_dot_dto_dot_Security__pb2
from hs.common.pb.hq.dto import OrderBook_pb2 as hq_dot_dto_dot_OrderBook__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hq/notify/OrderBookFullNotify.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n.com.huasheng.quant.open.sdk.protobuf.hq.notifyB\030OrderBookFullNotifyProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#hq/notify/OrderBookFullNotify.proto\x1a\x15hq/dto/Security.proto\x1a\x16hq/dto/OrderBook.proto\"v\n\x13OrderBookFullNotify\x12\x1b\n\x08security\x18\x01 \x01(\x0b\x32\t.Security\x12\x0c\n\x04side\x18\x02 \x01(\x05\x12!\n\rorderBookList\x18\x03 \x03(\x0b\x32\n.OrderBook\x12\x11\n\tmktTmType\x18\x04 \x01(\x05\x42J\n.com.huasheng.quant.open.sdk.protobuf.hq.notifyB\x18OrderBookFullNotifyProtob\x06proto3'
  ,
  dependencies=[hq_dot_dto_dot_Security__pb2.DESCRIPTOR,hq_dot_dto_dot_OrderBook__pb2.DESCRIPTOR,])




_ORDERBOOKFULLNOTIFY = _descriptor.Descriptor(
  name='OrderBookFullNotify',
  full_name='OrderBookFullNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='security', full_name='OrderBookFullNotify.security', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='side', full_name='OrderBookFullNotify.side', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orderBookList', full_name='OrderBookFullNotify.orderBookList', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mktTmType', full_name='OrderBookFullNotify.mktTmType', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=204,
)

_ORDERBOOKFULLNOTIFY.fields_by_name['security'].message_type = hq_dot_dto_dot_Security__pb2._SECURITY
_ORDERBOOKFULLNOTIFY.fields_by_name['orderBookList'].message_type = hq_dot_dto_dot_OrderBook__pb2._ORDERBOOK
DESCRIPTOR.message_types_by_name['OrderBookFullNotify'] = _ORDERBOOKFULLNOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderBookFullNotify = _reflection.GeneratedProtocolMessageType('OrderBookFullNotify', (_message.Message,), {
  'DESCRIPTOR' : _ORDERBOOKFULLNOTIFY,
  '__module__' : 'hq.notify.OrderBookFullNotify_pb2'
  # @@protoc_insertion_point(class_scope:OrderBookFullNotify)
  })
_sym_db.RegisterMessage(OrderBookFullNotify)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
