# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plateform/vo/MemberOptionalStock.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='plateform/vo/MemberOptionalStock.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n1com.huasheng.quant.open.sdk.protobuf.plateform.voB\030MemberOptionalStockProto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n&plateform/vo/MemberOptionalStock.proto\"]\n\x13MemberOptionalStock\x12\x14\n\x0csecurityCode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x64\x61taType\x18\x03 \x01(\t\x12\x10\n\x08orderNum\x18\x04 \x01(\x05\x42M\n1com.huasheng.quant.open.sdk.protobuf.plateform.voB\x18MemberOptionalStockProtob\x06proto3'
)




_MEMBEROPTIONALSTOCK = _descriptor.Descriptor(
  name='MemberOptionalStock',
  full_name='MemberOptionalStock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='securityCode', full_name='MemberOptionalStock.securityCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='MemberOptionalStock.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dataType', full_name='MemberOptionalStock.dataType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orderNum', full_name='MemberOptionalStock.orderNum', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=135,
)

DESCRIPTOR.message_types_by_name['MemberOptionalStock'] = _MEMBEROPTIONALSTOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MemberOptionalStock = _reflection.GeneratedProtocolMessageType('MemberOptionalStock', (_message.Message,), {
  'DESCRIPTOR' : _MEMBEROPTIONALSTOCK,
  '__module__' : 'plateform.vo.MemberOptionalStock_pb2'
  # @@protoc_insertion_point(class_scope:MemberOptionalStock)
  })
_sym_db.RegisterMessage(MemberOptionalStock)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
